spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://211.110.44.79:3306/bon_dev
    username: itadmin
    password: gthkds!83!
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        show-sql: true
        format-sql: true
    hibernate:
      ddl-auto: update

  web:
    resources:
      static-locations:
        - classpath:/static/
        - classpath:/public/
        - classpath:/resources/
        - classpath:/META-INF/resources/
        - file:///uploads/images/

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    root: INFO # 전체 애플리케이션 기본 로그 레벨
    org.springframework: WARN # 스프링 관련 로그 경고(WARN) 이상만 출력
    bon.bon_jujitsu: DEBUG # 특정 패키지(bon.bon_jujitsu) 로그 디버그(DEBUG) 모드 활성화
    org.springframework.web: DEBUG # Spring Web 로그 디버그(DEBUG) 모드 활성화
    org.springframework.jdbc: DEBUG # Spring JDBC 로그 디버그(DEBUG) 모드 활성화
    org.springframework.transaction: DEBUG # Spring 트랜잭션 로그 디버그(DEBUG) 모드 활성화

filepath: /uploads/images/
