spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://211.110.44.28:3306/bon_dev
    username: itadmin
    password: kdsgth!84!
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        show-sql: false
        format-sql: false
    hibernate:
      ddl-auto: update
    logging:
      level:
        org.hibernate.SQL: info
        org.springframework.web: DEBUG
        org.springframework.boot: DEBUG

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

filepath: /data/uploads/bon/

app:
  base-url: http://bon-dev.ezylab.co.kr