spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://211.110.44.79:3306/bon_dev
    username: itadmin
    password: gthkds!83!
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        show-sql: true
        format-sql: true
    hibernate:
      ddl-auto: update
    logging:
      level:
        org.hibernate.SQL: debug
        org.springframework.web: DEBUG
        org.springframework.boot: DEBUG
  web:
    resources:
      static-locations: file:///uploads/images/

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

filepath: /uploads/images/
