spring:
  application:
    name: Bon
  profiles:
    active: dev
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

filepath: /data/uploads/bon/

app:
  base-url: http://bon-dev.ezylab.co.kr
