package bon.bon_jujitsu.domain;

public enum Region {
  // 서울
  SEOUL_DANGSAN,
  SEOUL_SHINLIM,
  SEOUL_MUNLAE,

  // 인천
  INCHEON_NAEPO,
  INCHEON_GUWOL,
  INCHEON_JUAN,
  INCHEON_DONGCHUN,
  INCHEON_SAMSAN,
  INCHEON_GAJUNG,
  INCHEON_YUNGJONGDO,
  INCHEON_NONHYEON,

  // 경기
  GUNPO_GUNPO,
  HWASUNG_BYEONJUM,
  PYEONGTAK_SONGTAN,
  ANSAN_SUNBU,
  HWASUNG_DONGTAN,
  PYEONGTAK_ANJUNG,
  OSAN_OSAN,
  HWASUNG_HYANGNAM,
  SHIHEUNG_BAEGOT,
  HWASUNG_SONGSAN,
  SHIHEUNG_SHINCEON,
  PYEONGTAK_SOSABUL,
  YONGIN_HEUNGDEOK,
  HWASUNG_NAMYANG,
  HWASUNG_BONGDAM,
  SUWON_WONCHEON,
  UIWANG_UIWANG,
  PYEONGTAK_PANGSUNG,
  OSAN_UNAM,
  GWANGMYEONG_HAAN,
  ANYANG_BUMGAE,
  SUNGNAM_DAEJANG,
  YANGJU_HOECHEON,
  GOYANG_CHANGLENG,
  YANGPYEONG_YANGPYEONG,
  ANSAN_SUNGPO,
  OSAN_GWOULDONG,
  ANSUNG_GONGDO,
  SHIHEUNG_WOLGOD,
  PYEONGTAK_SAEGYO,

  // 충청
  JECHEON_HASO,
  JECHEON_JANGLAK,
  JINCEON_JINCEON,
  HONGSUNG_NAEPOE
}
